@startuml
note as n1
const tv = new Tv();
const remote = new RemoteControl(tv);
remote.togglePower();
end note

abstract Device {
    + isEnabled(): boolean {};
    + enable(): void {};
    + disable(): void {};
}

class Tv extends Device {
}

class RemoteControl {
    - protected device: Device;
    + constructor(device: Device) {}
    + togglePower() {}
}

class AdvancedRemoteControl extends RemoteControl {
    + mute() {}
}

RemoteControl *- Device
@enduml