@startuml
note as n1
const redCircle = new Circle(new Red());
redCircle.setShape("circle");
redCircle.setColor("red");
end note

class Shape {
    + type: string;
    + color: Color;
    + constructor(color: Color) {}
    + getShape() {}
    + setShape() {}
}

class Circle extends Shape {}
class Square extends Shape {}

abstract Color {
    + type: string;
    + getColor(): string
    + setColor(): void
}

class Red extends Color {
}

class Blue extends Color {
}

Shape *-> Color
@enduml